name: .NET Web APP CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restore dependencies
      run: dotnet restore StoreApi/StoreApi.csproj

    - name: Build
      run: dotnet build StoreApi/StoreApi.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test Tests/Tests.csproj --no-build --configuration Release --verbosity normal

    - name: Publish Artifact
      run: dotnet publish StoreApi/StoreApi.csproj --no-build --configuration Release --output ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-api-drop
        path: ./backend/publish